### ISSUE TITLE
Ruby group capstone: set up Kanban board

### ISSUE THREAD

**Issue by K0ppai** [K0ppai/My-Catalog#22]
Hello Reviewers,
- We have 3 members in our team @sunga12 (Team member 1), @K0ppai (Team member 2), @batoolfatima2135 (Team member 3)
- This is the [link](https://github.com/K0ppai/My-Catalog/projects/1) of our project.

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

![](https://media.giphy.com/media/4WFFDhSWjNfa63W8sW/giphy.gif)

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)


# Hi @K0ppai, @batoolfatima2135 & @sunga12  👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- All information is provided in the issue ✔
- Correct template is used ✔
- Each team member is assigned a task ✔

## Required Changes ♻️
- This is a close one! but it seems @K0ppai (Team member 2) is not assigned one of the tasks which is shown in the below screenshot, I'd kindly suggest you add the card to ensure all tasks have been implemented, Keep up the great work guys!
  ![image](https://github.com/K0ppai/My-Catalog/assets/104968236/ff267d7a-8545-4fcf-854e-05c65c68580d)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ichala** [comment]
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
